name: test bigballR

on:
  workflow_dispatch:

jobs:
  test-bigball:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("remotes","curl"))'
          Rscript -e 'remotes::install_github("lbenz730/bigballR")'

      - name: Test bigballR (minimal)
        run: |
          Rscript -e '
            library(bigballR)
            Sys.setenv(
              BIGBALLR_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
            )
            message("Calling bigballR testâ€¦")
            x <- tryCatch(
              {
                bb_player_stat_totals(
                  season = 2024,
                  stat = "pts"
                )
              },
              error = function(e) e
            )
            print(x)
          '
