name: test bigballR

on:
  workflow_dispatch:

jobs:
  test-bigball:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libcairo2-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff5-dev


      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages(c("remotes","curl","ggforce","ggraph"), dependencies = TRUE)'
          Rscript -e 'remotes::install_github("jflancer/bigballR", upgrade = "never")'



      - name: Test bigballR (minimal)
        run: |
          Rscript -e '
            library(bigballR)
            Sys.setenv(
              BIGBALLR_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
            )
            message("Calling bigballR testâ€¦")
            x <- tryCatch(
              {
                bb_player_stat_totals(
                  season = 2024,
                  stat = "pts"
                )
              },
              error = function(e) e
            )
            print(x)
          '
